# Generated by Django 5.0.6 on 2024-08-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images/blog')),
                ('name', models.CharField(max_length=80)),
                ('jobs', models.CharField(max_length=50)),
            ],
        ),
    ]
